name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Build (check it compiles)
        run: cargo build --release

      # Set up Docker Compose
      - name: Set up Docker Compose environment
        run: docker compose up -d postgres prometheus garbagetruck

      - name: Wait for Postgres to be healthy
        run: |
          for i in {1..30}; do
            docker compose exec postgres pg_isready -U testuser -d testdb && break
            sleep 2
          done

      - name: Run tests
        run: cargo test --all

      # Optionally run more integration/comprehensive tests
      - name: Run integration.rs
        run: cargo test --test integration || true

      - name: Run comprehensive shell tests
        run: |
          if [ -f ./scripts/comprehensive_test.sh ]; then
            bash ./scripts/comprehensive_test.sh
          fi

      - name: Tear down docker compose
        run: docker compose down -v

      - name: Collect docker logs
        if: failure()
        run: docker compose logs
